### ISSUE TITLE
Error with SDD.py

### ISSUE THREAD

**Issue by cinout** [zqhang/AnomalyCLIP#10]
Dear author,

I encountered an issue with running SDD.py. 

> No such file or directory: 'data/sdd/electrical commutators/train'

Can you tell me why the SDD dataset has class "electrical commutators"? I can only see classnames such as "kos35", "kos36", etc. in the datasets.

Thank you.

**Comment by zqhang** [comment]
You need to pre-process SDD dataset according to this [script](https://github.com/Choubo/DRA/blob/main/data/convert_SDD.py). Then, you can create a folder named "electrical commutator" like MVTec AD.

**Comment by zqhang** [comment]
It may affect the baselines, but AnomalyCLIP does not necessitate prior text class names. Instead, these are replaced with the term 'object'.
