### ISSUE TITLE
 When will the source code be released?

### ISSUE THREAD

**Issue by shining-love** [zqhang/AnomalyCLIP#2]
+1

**Comment by cryingdxy** [comment]
+1

**Comment by ladch** [comment]
+1

**Comment by 7HHHHH** [comment]
111

**Comment by ygjwd12345** [comment]
+1

**Comment by zqhang** [comment]
Thanks for your attention. I've been busy with other deadlines and wrapping up projects lately. Once I finish these works, I will open source. It takes about a week maybe shorter

**Comment by lyy70** [comment]
Does v-attention alone not lose information? I did this work,  inspired by AnoVL, But the performance is a little worse than before.
Looking forward to your code, it would be very helpful.

**Comment by Wangjinhong1998** [comment]
> Thanks for your attention. I've been busy with other deadlines and wrapping up projects lately. Once I finish these works, I will open source. It takes about a week maybe shorter

Can this be completed and released this week?  thank you

**Comment by ladch** [comment]
Looking forward to your open source release as soon as possible!

**Comment by endeavor-FF** [comment]
+1

**Comment by jhpang32** [comment]
+1

**Comment by cryingdxy** [comment]
when will the code will be released?

**Comment by tianyu0207** [comment]
Hi Code has been released thanks for your interest.
