### ISSUE TITLE
The learnable token embeddings are attached to the first 9 layers of the text encoder for refining the textual space.

### ISSUE THREAD

**Issue by phusinhngay2011** [zqhang/AnomalyCLIP#21]
![Ảnh chụp màn hình 2024-06-08 214758](https://github.com/zqhang/AnomalyCLIP/assets/105209739/3fe20f73-9e94-4d7f-8d4d-da58f801a163)
First of all, I would like to thank you and your colleagues for your contributions to this domain. I have a question that in the `Implementation details` you said that `The learnable token embeddings are attached to the first 9 layers of the text encoder for refining the textual space.` but I only see that the `2nd (i = 1)` -> `8th (i = 7)` layers are attached. Can you explain it for me, thank you.

**Comment by zqhang** [comment]
we do not attach text embedding at the first layer，and attach embedding for the next 8 layers (9-th layer)



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/08/2024 23:25 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [zqhang/AnomalyCLIP] The learnable token embeddings are attached to the first 9 layers of the text encoder for refining the textual space. (Issue #21) |

nh.ch.p.man.hinh.2024-06-08.214758.png (view on web)
First of all, I would like to thank you and your colleagues for your contributions to this domain. I have a question that in the Implementation details you said that The learnable token embeddings are attached to the first 9 layers of the text encoder for refining the textual space. but I only see that the 2nd (i = 1) -> 8th (i = 7) layers are attached. Can you explain it for me, thank you.

**Comment by phusinhngay2011** [comment]
Thank you for clarifying, I just figure out the 9-th layer also attached.
