### ISSUE TITLE
作者大大你好，请问zero-shot如何体现呢？

### ISSUE THREAD

**Issue by Justhuayu** [zqhang/AnomalyCLIP#28]
请问在您的工作中，zero-shot是如何体现的呢？既然是zero-shot，那么为什么会训练mvtec数据集，然后测试mvtec数据集的性能指标呢？最后还有一个问题，为什么在训练和测试的时候，都用的测试数据集呢？

**Comment by zqhang** [comment]
1、AnomalyCLIP使用辅助数据集对CLIP进行微调，然后在目标数据上直接测试。
2、论文中除了MVTec之外的其他结果都是使用MVTec数据集进行微调的，MVTec的结果则是使用Visa数据集进行微调的。
3、使用测试集是因为AnomalyCLIP需要异常样本来学习通用的异常模式。

**Comment by Justhuayu** [comment]
明白了，非常感谢🙏
