### ISSUE TITLE
DPAM层的意义是什么

### ISSUE THREAD

**Issue by wliu23** [zqhang/AnomalyCLIP#43]
您好，在您的论文中提到DPAM改用了v-v自注意力，但在代码中，vit的输出似乎被设定为输出原始的x_ori，那么这和原始clip有什么区别呢？
![微信图片_20240830154910](https://github.com/user-attachments/assets/c9d0c9ba-1af1-4705-bf8e-84d74560325d)

**Comment by Xantastic** [comment]
> 您好，在您的论文中提到DPAM改用了v-v自注意力，但在代码中，vit的输出似乎被设定为输出原始的x_ori，那么这和原始clip有什么区别呢？ ![微信图片_20240830154910](https://private-user-images.githubusercontent.com/169225304/363089778-c9d0c9ba-1af1-4705-bf8e-84d74560325d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDc0OTAsIm5iZiI6MTczMzkwNzE5MCwicGF0aCI6Ii8xNjkyMjUzMDQvMzYzMDg5Nzc4LWM5ZDBjOWJhLTFhZjEtNDcwNS1iZjhlLTg0ZDc0NTYwMzI1ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQwODUzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01OGJiZGYyNTVhZWYxNjUwZDllMDAxNzNkYjBkNmEyOWMwYjMxY2FhMjRhMjEyYTM3YjZhYjgxYmJlYjg0YzczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZEVp6JxyDc0leZhfYn3mDzinvSdpsOgY29oWOrh6AVA)

我也有一样的疑惑，请问您最后是怎么解决的呀？
