### ISSUE TITLE
About DPAM Layer

### ISSUE THREAD

**Issue by yjnanan** [zqhang/AnomalyCLIP#55]
Dear authors,

I appreciate your excellent work. However, I notice that v-v attention is not used in your released code, why use x_ori in your code?
![image](https://github.com/user-attachments/assets/936cc07a-0e13-4ad5-976e-f880376d89d8)
![image](https://github.com/user-attachments/assets/dddfe290-8e81-480b-ac8a-cbb06f57e033)

**Comment by Xantastic** [comment]
> Dear authors,
> 
> I appreciate your excellent work. However, I notice that v-v attention is not used in your released code, why use x_ori in your code? ![image](https://private-user-images.githubusercontent.com/73676444/390612316-936cc07a-0e13-4ad5-976e-f880376d89d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDU3ODgsIm5iZiI6MTczMzkwNTQ4OCwicGF0aCI6Ii83MzY3NjQ0NC8zOTA2MTIzMTYtOTM2Y2MwN2EtMGUxMy00YWQ1LTk3NmUtZjg4MDM3NmQ4OWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzOTIzM2Q5NmNkNDM4NDJlNGYwMWViNWQ4YzUzNGUyOWRjZDRmMjk0ODhkMDkzNjc0ZWI2NzIwOWVjMTU3MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PtNlz0_uoAbZNpRzxYPm_UFGCp-QM8re3uaSO1vYLfk) ![image](https://private-user-images.githubusercontent.com/73676444/390612430-dddfe290-8e81-480b-ac8a-cbb06f57e033.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MDU3ODgsIm5iZiI6MTczMzkwNTQ4OCwicGF0aCI6Ii83MzY3NjQ0NC8zOTA2MTI0MzAtZGRkZmUyOTAtOGU4MS00ODBiLWFjOGEtY2JiMDZmNTdlMDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDA4MjQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNTY5Zjk0YWVlOTdlY2ZiZGE2Yzc2MmZmYWI3ZTdkMDA4MjM4ZDg3ZTUxNWI3OGM0ZTJjNjBiYzY4MjZkYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.l_caL1jvjMVhzfi419fR6Jgs9v-roksEeRYERx_8axc)

I've also noticed this problem. The author's code didn't utilize the V-V attention mechanism proposed in the paper. Could you please tell me how it was solved  #later?
