### ISSUE TITLE
Pure leakage in the test set

### ISSUE THREAD

**Issue by FudaMingdaXsc** [zqhang/AnomalyCLIP#9]
It seems that you used the entire test set to train encode_text_learn, while also using the test set for testing, which is seriously inconsistent with the ZERO-SHOT mentioned in your paper.Can you explain this issue

**Comment by zqhang** [comment]
We conduct zero-shot performance evaluations on datasets other than MVTEC AD using the test set of MVTEC AD dataset. And, we assess the zero-shot performance on the MVTEC AD dataset using the test set of VisA dataset. This aligns with the approach presented in our paper. You can check the script [train.sh](https://github.com/zqhang/AnomalyCLIP/blob/main/train.sh) and [test.sh](https://github.com/zqhang/AnomalyCLIP/blob/main/test.sh)

**Comment by zqhang** [comment]
Thanks for your acknowledgment, I will close this issue.
